version: '3.4'

services:
  mimic.api:
    image: mimicapi
    build:
      context: .
      dockerfile: src/Mimic.API/Dockerfile
    container_name: mimicapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
      - ConnectionStrings__SQLite=Data Source=Mimic.db
      - SwaggerEnabled=true
    ports:
      - "443:80"