version: '3.4'

services:
  mimic.api:
    image: ${DOCKER_REGISTRY-}mimic
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src\Mimic.API\Dockerfile